### ISSUE TITLE
Support for page constructor injections ?

### ISSUE THREAD

**Issue by Strypper** [dpaulino/UwpDependencyInjectionSample#1]
Can we make a constructor injection for `Page` ?
```cs
        public MainPage()
        {
            this.InitializeComponent();
            _classWithDI = App.Services.GetRequiredService<ClassWithDI>();
            Greeting.Text = _classWithDI.GetGreeting();
        }
```

**Comment by dpaulino** [comment]
Constructor injection in a Page is not possible if I recall correctly. The Page is constructed inside Frame during navigation. You don't construct it manually. In other words, you never do "new Page()". Thus, we can't do constructor injection with Page. 

The approach shown in this repository is what I would recommend for Page instead of constructor injection.

**Comment by Strypper** [comment]
Thanks for clarifying this, I didn't think things that are possible in MAUI could archive in UWP and Windows SDK
